format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$deno\
$golang\
$java\
$nodejs\
$rust\
[](fg:#86BBD8 bg:#06969A)\
$package\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[](fg:#33658A)\
$status \n\
$character"""

# Disable the blank line at the start of the prompt
add_newline = true
command_timeout = 2000

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vimcmd_symbol = " [<](bold green)"

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = '🔒'
read_only_style = 'red'

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[deno]
symbol = "🦕 "
style = "bg:#06969A"
format = '[ $symbol($version )]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_commit]
disabled = false
commit_hash_length = 7
format = "[\\($hash\\)]($style)"
style = 'bg:#FCA17D'
only_detached = false
tag_disabled = true

[git_status]
style = "bg:#FCA17D"
format = '[ $all_status $ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[package]
symbol = "📦"
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[status]
disabled = false
symbol = " ✖ "
success_symbol = " ✔️ "
not_executable_symbol = " 🚫 "
not_found_symbol = " 🔍"
sigint_symbol = " ⚡"
signal_symbol = " ⚡"
map_symbol = true
pipestatus = true

[time]
disabled = false
time_format = "%R[%p] %a"
style = "bg:#33658A"
format = '[ 🕓︎$time ]($style)'
